export const mockedMessages = [
  { message: 'Olá, tudo bem?', userName: 'john', timeStamp: '07:38:03' },
  { message: 'Sim, e contigo?', userName: 'mary', timeStamp: '07:39:05' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'O que está fazendo agora?', userName: 'john', timeStamp: '07:39:15' },
  { message: 'Nada. E você?', userName: 'mary', timeStamp: '07:39:27' },
  { message: 'Estava estudando', userName: 'john', timeStamp: '07:39:37' },
  { message: 'É bom né!?', userName: 'mary', timeStamp: '07:39:47' },
  { message: 'É necessário', userName: 'john', timeStamp: '07:39:57' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },

];