export const mockedMessages = [
  { message: 'Olá, tudo bem?', userName: 'john', timeStamp: '07:38:03' },
  { message: 'Sim, e contigo?', userName: 'mary', timeStamp: '07:39:05' },
  { message: 'Tudo ótimo!', userName: 'john', timeStamp: '07:39:07' },
  { message: 'O que está fazendo agora?', userName: 'john', timeStamp: '07:39:15' },
  { message: 'Nada. E você?', userName: 'mary', timeStamp: '07:39:27' },
  { message: 'Estava estudando', userName: 'john', timeStamp: '07:39:37' },
  { message: 'É bom né!?', userName: 'mary', timeStamp: '07:39:47' },
  { message: 'É necessário', userName: 'john', timeStamp: '07:39:57' },
  { message: 'Pois é', userName: 'mary', timeStamp: '07:39:07' },
  { message: 'Pois é né', userName: 'john', timeStamp: '07:39:17' },
  { message: 'Então...', userName: 'mary', timeStamp: '07:39:27' },
  { message: 'Já volto, vou lanchar', userName: 'john', timeStamp: '07:39:37' },
  { message: 'Ok', userName: 'mary', timeStamp: '07:39:47' },
  { message: 'Voltei', userName: 'john', timeStamp: '07:45:57' },
  { message: 'O que vc lanchou?', userName: 'mary', timeStamp: '07:45:07' },
  { message: 'Um hot dog.', userName: 'john', timeStamp: '07:45:07' },
  { message: 'Hmmmmm', userName: 'mary', timeStamp: '07:45:07' },
  { message: 'Gosta?', userName: 'john', timeStamp: '07:45:07' },
  { message: 'Sou vegana.', userName: 'mary', timeStamp: '07:45:17' },
  { message: 'Ah sim...', userName: 'john', timeStamp: '07:45:27' },
  { message: 'Enquanto vc lanchava, adivinha o que fiz...', userName: 'mary', timeStamp: '07:45:37' },
  { message: 'O que??', userName: 'john', timeStamp: '07:45:47' },
  { message: 'Estudei!', userName: 'mary', timeStamp: '07:45:57' },
  { message: 'Nossa! É bom demais né!', userName: 'john', timeStamp: '07:46:07' },
  { message: 'Sim!!!', userName: 'mary', timeStamp: '07:46:07' },
  { message: 'Estudou o que?', userName: 'john', timeStamp: '07:46:17' },
  { message: 'Como criar um chat.', userName: 'mary', timeStamp: '07:46:27' },
  { message: 'E conseguiu?', userName: 'john', timeStamp: '07:46:37' },
  { message: 'Consegui.', userName: 'mary', timeStamp: '07:46:47' },
  { message: 'Dejavu.', userName: 'john', timeStamp: '07:46:57' },

];